# Generated by Django 5.0.6 on 2024-05-30 06:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_delete_groupcomment'),
        ('tasks', '0002_tasks_user_taskdownload_delete_groupcomments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasks',
            name='process',
        ),
        migrations.AddField(
            model_name='taskcomments',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='tasks/'),
        ),
        migrations.CreateModel(
            name='Process',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('process', models.PositiveSmallIntegerField(choices=[(1, 'New'), (2, 'In Process'), (3, 'Pending'), (4, 'done'), (5, 'Cansel')], default=1)),
                ('tasks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_process', to='tasks.tasks')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processes', to='accounts.worker')),
            ],
        ),
        migrations.DeleteModel(
            name='TaskDownload',
        ),
    ]
