# Generated by Django 5.0.6 on 2024-05-22 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worker',
            name='position',
            field=models.PositiveSmallIntegerField(choices=[(1, 'leader'), (2, 'Group leader'), (3, 'Worker')], default=3),
        ),
        migrations.DeleteModel(
            name='Position',
        ),
    ]
