# Generated by Django 5.0.6 on 2024-05-22 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_worker_position_delete_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='worker_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='worker',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='groups', to='accounts.group'),
        ),
    ]
